### ISSUE TITLE
git checkout error

### ISSUE THREAD

**Issue by tamtakoe** [shipitjs/shipit-deploy#82]
Shipit can't checkout from `master` to `develop` because git finds some local changes. It is strange. I make `git clone` and get absolutely clean repository without uncommitted files. I don't know where are its uncommitted files and how I can commit or stash (when I commit or stash in repository directory, git doesn't see uncommitted files, tmp folder is clean).
```sh
Running 'deploy:init' task...
Finished 'deploy:init' after 1.16 ms

Running 'deploy:fetch' task...
Create workspace "/tmp/project/client"
Workspace created.
Initialize local repository in "/tmp/project/client"
Running "git init" on local.
@ Reinitialized existing Git repository in /tmp/project/client/.git/
Repository initialized.
List local remotes.
Running "git remote" on local.
@ shipit
Update remote "git@bitbucket.org:test/project-client.git" to local repository "/tmp/project/client"
Running "git remote set-url shipit git@bitbucket.test/project-client.git" on local.
Remote updated.
Fetching repository "git@bitbucket.org:test/project-client.git"
Running "git fetch shipit -p" on local.
Repository fetched.
Checking out commit-ish "develop"
Running "git checkout develop" on local.
@ error: Your local changes to the following files would be overwritten by checkout:
@       projects/compiled/main/vendor/angularBootstrap.js
@       projects/compiled/main/vendor/angularStrap.js
@ Please, commit your changes or stash them before you can switch branches.
@ Aborting
'deploy:fetch' errored after 6.29 s
Error: Command failed: /bin/sh -c git checkout develop
error: Your local changes to the following files would be overwritten by checkout:
        projects/compiled/main/vendor/angularBootstrap.js
        projects/compiled/main/vendor/angularStrap.js
Please, commit your changes or stash them before you can switch branches.
Aborting

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Unhandled rejection Error: Command failed: /bin/sh -c git checkout develop
error: Your local changes to the following files would be overwritten by checkout:
        projects/compiled/main/vendor/angularBootstrap.js
        projects/compiled/main/vendor/angularStrap.js
Please, commit your changes or stash them before you can switch branches.
Aborting

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by tamtakoe** [comment]
I solved the problem. Uncommitted files exist in the tmp directory where the build was made, not on the server where be deploy build

**Comment by neoziro** [comment]
@tamtakoe yes there can be some issue if your git repository is not "clean"

**Comment by cstengel88** [comment]
Could someone explain how to solve it plz
